# ---------------------------------------------------------------
# app2.example.com  →  https://backend-server-2:443
# ---------------------------------------------------------------

server {
    listen 443 ssl;
    http2  on;
    server_name app2.example.com;

    ssl_certificate     /etc/nginx/certs/app2.example.com/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/app2.example.com/privkey.pem;
    include /etc/nginx/snippets/ssl-params.conf;

    location / {
        include /etc/nginx/snippets/proxy-params.conf;
        proxy_pass https://backend-server-2:443;
    }
}
