server {
    listen 443 ssl;
    http2  on;
    server_name ice.ignition.net.nz;

    ssl_certificate     /etc/nginx/certs/live/ice.ignition.net.nz/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/live/ice.ignition.net.nz/privkey.pem;
    include /etc/nginx/snippets/ssl-params.conf;

    location / {
        include /etc/nginx/snippets/proxy-params.conf;
        proxy_pass https://ice-backend.ignition.net.nz:443;

        add_header Cross-Origin-Opener-Policy   "same-origin"   always;
        add_header Cross-Origin-Embedder-Policy "require-corp"  always;
    }
}

server {
    listen 8443 ssl;
    http2  on;
    server_name ice.ignition.net.nz;

    ssl_certificate     /etc/nginx/certs/live/ice.ignition.net.nz/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/live/ice.ignition.net.nz/privkey.pem;
    include /etc/nginx/snippets/ssl-params.conf;

    location / {
        include /etc/nginx/snippets/proxy-params.conf;
        proxy_pass https://ice-backend.ignition.net.nz:8443;

        add_header Cross-Origin-Opener-Policy   "same-origin"   always;
        add_header Cross-Origin-Embedder-Policy "require-corp"  always;
    }
}
